### ISSUE TITLE
Locality preferences for settings.py

### ISSUE THREAD

**Issue by DanOBrien** [owntracks/backend#14]
It would be nice to have a "locality" setting or flag in the m2s config to convert Epoch time to my local time zone and celsius to fahrenheit.

Here's how I hacked it for my server.

I edited m2s.py, line 193. Changed time.gmtime to time.localtime.

For pl-weather.py, I changed line 20 to:
self.url = 'http://api.openweathermap.org/data/2.5/weather?%s&units=imperial'

(You could do away with the conversion from Kelvin by using &units=metric instead of imperial)

On line 34, I just took out the conversion from Kelvin:
celsius = "%0.1f" % (float(weather_data['main']['temp']))
 
and on line 69 I changed the notation from C to F
value = "%s %sF" % (w['current'], w['celsius'])

purged my database and started tracking myself again. I'll probably have some weird data when Daylight Savings starts, but I can manage. Who likes Daylight Savings time anyway? NOT ME!

**Comment by jpmens** [comment]
Thanks for that.

Please be advised, that m2s is slowly fading away ... You may be interested in our new backend called [pista](https://github.com/owntracks/pista) 

[blog post](http://blog.owntracks.org/post/106889564956/introducing-pista-the-new-owntracks-back-end).

**Comment by DanOBrien** [comment]
Awesome, I'll take a peek! Thanks!

**Comment by jpmens** [comment]
Closing b/c this is implemented in `o2s` and `pista`.
